---

- name: Create server Openstack
  hosts: localhost
  tasks:
    - name: Create infrastructure using TOSCA template
      clouni:
        template_file: tosca-server-example.yaml
        provider: openstack
        cluster_name: testing_ansible
      register: output_data

    - debug:
        var: output_data