---
- name: 'Delete OpenStack component openstack cluster: tosca_server_example_floating_ip:delete'
  hosts: localhost
  tasks:
  - include_vars: id_vars_example.yaml
  - name: Delete OpenStack component floating ip
    os_floating_ip:
      name: '{{ tosca_server_example_floating_ip_delete }}'
      state: absent
    when: tosca_server_example_floating_ip_delete is defined
    register: tosca_server_example_floating_ip_var
  - set_fact: tosca_server_example_floating_ip='{{ tosca_server_example_floating_ip_var
      }}'
    when: tosca_server_example_floating_ip_var.changed
  - name: Delete OpenStack component floating ip
    os_floating_ip:
      name: '{{ item }}'
      state: absent
    when: tosca_server_example_floating_ip_ids is defined
    loop: '{{ tosca_server_example_floating_ip_ids | flatten(levels=1) }}'
    register: tosca_server_example_floating_ip_var
  - set_fact: tosca_server_example_floating_ip='{{ tosca_server_example_floating_ip_var
      }}'
    when: tosca_server_example_floating_ip_var.changed
  - name: Delete OpenStack component floating ip
    os_floating_ip: '{{ item }}'
    loop: '{{ tosca_server_example_floating_ip_dicts }}'
    when: tosca_server_example_floating_ip_dicts is defined
    register: tosca_server_example_floating_ip_var
  - set_fact: tosca_server_example_floating_ip='{{ tosca_server_example_floating_ip_var
      }}'
    when: tosca_server_example_floating_ip_var.changed
- name: 'Delete OpenStack component openstack cluster: tosca_server_example_server:delete'
  hosts: localhost
  tasks:
  - include_vars: id_vars_example.yaml
  - name: Delete OpenStack component server
    os_server:
      name: '{{ tosca_server_example_server_delete }}'
      state: absent
    when: tosca_server_example_server_delete is defined
    register: tosca_server_example_server_var
  - set_fact: tosca_server_example_server='{{ tosca_server_example_server_var }}'
    when: tosca_server_example_server_var.changed
  - name: Delete OpenStack component server
    os_server:
      name: '{{ item }}'
      state: absent
    when: tosca_server_example_server_ids is defined
    loop: '{{ tosca_server_example_server_ids | flatten(levels=1) }}'
    register: tosca_server_example_server_var
  - set_fact: tosca_server_example_server='{{ tosca_server_example_server_var }}'
    when: tosca_server_example_server_var.changed
  - name: Delete OpenStack component server
    os_server: '{{ item }}'
    loop: '{{ tosca_server_example_server_dicts }}'
    when: tosca_server_example_server_dicts is defined
    register: tosca_server_example_server_var
  - set_fact: tosca_server_example_server='{{ tosca_server_example_server_var }}'
    when: tosca_server_example_server_var.changed
- name: 'Delete OpenStack component openstack cluster: tosca_server_example_keypair:delete'
  hosts: localhost
  tasks:
  - include_vars: id_vars_example.yaml
  - name: Delete OpenStack component keypair
    os_keypair:
      name: '{{ tosca_server_example_keypair_delete }}'
      state: absent
    when: tosca_server_example_keypair_delete is defined
    register: tosca_server_example_keypair_var
  - set_fact: tosca_server_example_keypair='{{ tosca_server_example_keypair_var }}'
    when: tosca_server_example_keypair_var.changed
  - name: Delete OpenStack component keypair
    os_keypair:
      name: '{{ item }}'
      state: absent
    when: tosca_server_example_keypair_ids is defined
    loop: '{{ tosca_server_example_keypair_ids | flatten(levels=1) }}'
    register: tosca_server_example_keypair_var
  - set_fact: tosca_server_example_keypair='{{ tosca_server_example_keypair_var }}'
    when: tosca_server_example_keypair_var.changed
  - name: Delete OpenStack component keypair
    os_keypair: '{{ item }}'
    loop: '{{ tosca_server_example_keypair_dicts }}'
    when: tosca_server_example_keypair_dicts is defined
    register: tosca_server_example_keypair_var
  - set_fact: tosca_server_example_keypair='{{ tosca_server_example_keypair_var }}'
    when: tosca_server_example_keypair_var.changed
- name: 'Delete OpenStack component openstack cluster: tosca_server_example_security_group:delete'
  hosts: localhost
  tasks:
  - include_vars: id_vars_example.yaml
  - name: Delete OpenStack component security group
    os_security_group:
      name: '{{ tosca_server_example_security_group_delete }}'
      state: absent
    when: tosca_server_example_security_group_delete is defined
    register: tosca_server_example_security_group_var
  - set_fact: tosca_server_example_security_group='{{ tosca_server_example_security_group_var
      }}'
    when: tosca_server_example_security_group_var.changed
  - name: Delete OpenStack component security group
    os_security_group:
      name: '{{ item }}'
      state: absent
    when: tosca_server_example_security_group_ids is defined
    loop: '{{ tosca_server_example_security_group_ids | flatten(levels=1) }}'
    register: tosca_server_example_security_group_var
  - set_fact: tosca_server_example_security_group='{{ tosca_server_example_security_group_var
      }}'
    when: tosca_server_example_security_group_var.changed
  - name: Delete OpenStack component security group
    os_security_group: '{{ item }}'
    loop: '{{ tosca_server_example_security_group_dicts }}'
    when: tosca_server_example_security_group_dicts is defined
    register: tosca_server_example_security_group_var
  - set_fact: tosca_server_example_security_group='{{ tosca_server_example_security_group_var
      }}'
    when: tosca_server_example_security_group_var.changed
- name: Renew id_vars_example.yaml
  hosts: localhost
  tasks:
  - file:
      path: id_vars_example.yaml
      state: absent